import type { PageGuide } from './types';
import {
  Package,
  Search,
  ArrowUpDown,
  Tag,
  Plus,
  Sparkles,
  Upload,
  FileSpreadsheet,
  DollarSign,
  AlertTriangle,
  CheckCircle,
  Layers,
} from 'lucide-react';

export const inventoryGuide: PageGuide = {
  pageId: 'inventory',
  pageTitle: 'Inventory',
  sections: [
    {
      id: 'inventory-search',
      title: 'Search Products',
      description: 'Type a product name, SKU code, or category to find items in your inventory. The table filters as you type.',
      whyItMatters: 'Quickly find a specific product when a customer asks about stock or pricing.',
      icon: Search,
      wizardStep: 'list',
    },
    {
      id: 'inventory-sort',
      title: 'Sort Dropdown',
      description: 'Choose how products are ordered in the list: Newest First, Name (A-Z), Price (Low to High), or Price (High to Low).',
      whyItMatters: 'Sort by price to find your cheapest or most expensive items, or by name to find alphabetically.',
      icon: ArrowUpDown,
      wizardStep: 'list',
    },
    {
      id: 'category-filter',
      title: 'Category Filter',
      description: 'Toggle category pills to show only products in specific categories. Each pill shows the category name and product count. Tap "Clear" to show all products again.',
      whyItMatters: 'Filter by category when managing stock for a specific product line — like all sarees or all bakery items.',
      icon: Tag,
      wizardStep: 'list',
    },
    {
      id: 'inventory-status-badge',
      title: 'Stock Status Badge',
      description: 'Each product shows a colour-coded status: green "In Stock" means plenty available. Amber "Low Stock" means running out. Red "Out of Stock" means none left. Blue "On-demand" means made to order.',
      whyItMatters: 'Check red and amber badges first — these are products you need to restock or mark as unavailable.',
      icon: Package,
      wizardStep: 'list',
    },
    {
      id: 'add-products-button',
      title: 'Add Products Button',
      description: 'Opens the intake wizard where you can add new products by typing them, speaking them, or importing from an Excel/CSV file.',
      whyItMatters: 'Start here when you have new products to add — the AI will parse your descriptions into structured inventory.',
      icon: Plus,
      wizardStep: 'list',
    },
    {
      id: 'ai-parse',
      title: 'AI Smart Assistant',
      description: 'Type or speak your product details in any format (like a shopping list) and the AI will parse them into structured products with names, prices, variants, and stock quantities. The format guide shows examples of what to type.',
      whyItMatters: 'No need to fill out forms one product at a time — dump your entire product list and the AI organises it for you.',
      icon: Sparkles,
      wizardStep: 'intake',
    },
    {
      id: 'manual-entry',
      title: 'Manual Single Entry',
      description: 'Opens a form to add one product at a time by filling in each field manually. Use this for single products where you want full control over every detail.',
      whyItMatters: 'Use this for complex products with many variants that the AI might not parse correctly.',
      icon: FileSpreadsheet,
      wizardStep: 'intake',
    },
    {
      id: 'excel-import',
      title: 'Import Excel / CSV',
      description: 'Drag and drop or click to upload an Excel (.xlsx) or CSV file. The system maps your spreadsheet columns to product fields automatically.',
      whyItMatters: 'If you already have a product list in a spreadsheet, import it directly instead of re-typing everything.',
      icon: Upload,
      wizardStep: 'intake',
    },
    {
      id: 'confirmation-summary',
      title: 'Financial Summary Bar',
      description: 'Shows four numbers before you save: total items to save, estimated total inventory value, average unit price, and how many variant rows and low stock alerts exist.',
      whyItMatters: 'Review these numbers to catch mistakes — if the total value looks wrong, check your prices before saving.',
      icon: DollarSign,
      wizardStep: 'confirm',
    },
    {
      id: 'confirm-save-button',
      title: 'Confirm & Save Button',
      description: 'Tap this to save all parsed products to your inventory. If there are duplicates, a warning banner will appear asking you to review before saving.',
      whyItMatters: 'Double-check the duplicate warning — saving duplicates creates confusion when managing stock later.',
      icon: CheckCircle,
      wizardStep: 'confirm',
    },
    {
      id: 'variant-table',
      title: 'Variant Spreadsheet',
      description: 'An editable grid inside each product card where you manage variants. Each row is a variant (size, colour, weight, etc.) with columns for price, stock quantity, and a delete button. Add new rows with "Add Row" and new attribute columns with "Add Column".',
      whyItMatters: 'Keep variant prices and stock counts accurate — this data is shown to customers when they browse your products.',
      icon: Layers,
      wizardStep: 'confirm',
    },
    {
      id: 'duplicate-warning',
      title: 'Duplicate Warning',
      description: 'A yellow banner that appears if the products you are about to save already exist in your inventory. It tells you which products are duplicates so you can review them before confirming.',
      whyItMatters: 'Do not ignore this — saving duplicates means you have to delete the extras manually later.',
      icon: AlertTriangle,
      wizardStep: 'confirm',
    },
  ],
};
