import type { BackendLead } from "./StreamTriage";

const minAgo = (n: number) => new Date(Date.now() - n * 60 * 1000).toISOString();
const hourAgo = (n: number) => new Date(Date.now() - n * 3600 * 1000).toISOString();

export const MOCK_LEADS: BackendLead[] = [
  // ──────────────────────────────────────
  // CLAIM NOW (base intent: ORDERING or pendingOrderAmount > 0)
  // ──────────────────────────────────────
  {
    id: "mock-cn-001",
    name: "Priya Sharma",
    contact: "+919876543210",
    channel: "WHATSAPP",
    lastActiveAt: minAgo(12),
    conversationId: "mock-conv-cn-001",
    lastMessage: "Can I pay by card? Need this delivered by Saturday, please confirm",
    intent: "ORDERING",
    status: "OPEN",
    assignedTo: null,
    priority: "URGENT",
    agentAssigned: null,
    pendingOrderAmount: 4500,
    aiScore: 92,
    daysSinceActive: 0,
    hasAutoReply: true,
    botRepliedAt: minAgo(10),
    reasoning: "Customer confirmed delivery date + payment method — strong buy signal. Similar patterns closed 85% of the time.",
    pastOrders: 1,
    lifetimeValue: 8200,
    matchedProduct: { name: "Blue Silk Saree", variant: "Size M", stock: 4, thumbnailUrl: "" },
    dropOffMinutes: 15,
  },
  {
    id: "mock-cn-002",
    name: "Rahul Verma",
    contact: "@rahul_v",
    channel: "INSTAGRAM",
    lastActiveAt: minAgo(5),
    conversationId: "mock-conv-cn-002",
    lastMessage: "Need this urgently! Can you DM me the catalog?",
    intent: "ORDERING",
    status: "OPEN",
    assignedTo: null,
    priority: "URGENT",
    agentAssigned: null,
    pendingOrderAmount: 12000,
    aiScore: 88,
    daysSinceActive: 0,
    hasAutoReply: false,
    botRepliedAt: null,
    reasoning: "Urgent request with clear purchase intent — high conversion probability. Instagram leads with this language convert at 78%.",
    pastOrders: 0,
    lifetimeValue: 0,
    matchedProduct: null,
    dropOffMinutes: 20,
  },
  {
    id: "mock-cn-003",
    name: "Meera Iyer",
    contact: "+918888777666",
    channel: "WHATSAPP",
    lastActiveAt: minAgo(30),
    conversationId: "mock-conv-cn-003",
    lastMessage: "I want to place a bulk order for Diwali — 20 silk sarees",
    intent: "ORDERING",
    status: "OPEN",
    assignedTo: null,
    priority: "URGENT",
    agentAssigned: null,
    pendingOrderAmount: 3200,
    aiScore: 95,
    daysSinceActive: 0,
    hasAutoReply: false,
    botRepliedAt: null,
    reasoning: "Bulk order inquiry for Diwali — high value opportunity. Previous bulk orders in this category closed within 2 hours.",
    pastOrders: 2,
    lifetimeValue: 35000,
    matchedProduct: { name: "Silk Saree (Bulk)", variant: "20 pcs · Assorted", stock: 45, thumbnailUrl: "" },
    dropOffMinutes: 30,
  },
  {
    id: "mock-cn-004",
    name: "Karthik Nair",
    contact: "karthik@email.com",
    channel: "WEBSITE",
    lastActiveAt: minAgo(10),
    conversationId: "mock-conv-cn-004",
    lastMessage: "Can you customise the sherwani in navy blue instead of maroon?",
    intent: "ORDERING",
    status: "OPEN",
    assignedTo: null,
    priority: "HIGH",
    agentAssigned: null,
    pendingOrderAmount: 8500,
    aiScore: 82,
    daysSinceActive: 0,
    hasAutoReply: true,
    botRepliedAt: minAgo(8),
    reasoning: "Customization request signals purchase intent. 73% of customization inquiries convert within 24 hours.",
    pastOrders: 0,
    lifetimeValue: 0,
    matchedProduct: { name: "Navy Blue Sherwani", variant: "Custom · Size XL", stock: 2, thumbnailUrl: "" },
    dropOffMinutes: 25,
  },

  // ──────────────────────────────────────
  // FOLLOW UP (base: aiScore >= 60 or SUPPORT intent)
  // ──────────────────────────────────────
  {
    id: "mock-fu-001",
    name: "Ananya Patel",
    contact: "+917654321098",
    channel: "WHATSAPP",
    lastActiveAt: minAgo(45),
    conversationId: "mock-conv-fu-001",
    lastMessage: "Is the blue silk saree available in size M?",
    intent: "SUPPORT",
    status: "OPEN",
    assignedTo: null,
    priority: "NORMAL",
    agentAssigned: null,
    pendingOrderAmount: null,
    aiScore: 65,
    daysSinceActive: 0,
    hasAutoReply: true,
    botRepliedAt: minAgo(40),
    reasoning: "Product availability question — moderate intent. Support inquiries about specific items convert 45% of the time.",
    pastOrders: 1,
    lifetimeValue: 5400,
    matchedProduct: { name: "Blue Silk Saree", variant: "Size M", stock: 4, thumbnailUrl: "" },
    dropOffMinutes: 20,
  },
  {
    id: "mock-fu-002",
    name: "Vikram Joshi",
    contact: "vikram@email.com",
    channel: "WEBSITE",
    lastActiveAt: hourAgo(2),
    conversationId: "mock-conv-fu-002",
    lastMessage: "Do you have size charts for men's kurtas?",
    intent: "BROWSING",
    status: "OPEN",
    assignedTo: null,
    priority: "NORMAL",
    agentAssigned: null,
    pendingOrderAmount: null,
    aiScore: 65,
    daysSinceActive: 0,
    hasAutoReply: false,
    botRepliedAt: null,
    reasoning: "Browsing size charts — early stage. These leads typically convert within a week if nurtured.",
    pastOrders: 0,
    lifetimeValue: 0,
    matchedProduct: null,
    dropOffMinutes: 60,
  },
  {
    id: "mock-fu-003",
    name: "Deepa Krishnan",
    contact: "@deepa_k",
    channel: "INSTAGRAM",
    lastActiveAt: minAgo(60),
    conversationId: "mock-conv-fu-003",
    lastMessage: "Do you have this in green? Saw your reel on the new collection",
    intent: "SUPPORT",
    status: "OPEN",
    assignedTo: null,
    priority: "NORMAL",
    agentAssigned: null,
    pendingOrderAmount: null,
    aiScore: 70,
    daysSinceActive: 0,
    hasAutoReply: true,
    botRepliedAt: minAgo(55),
    reasoning: "Engaged with Instagram reel — strong visual interest. Similar engagement patterns led to 62% conversion last month.",
    pastOrders: 0,
    lifetimeValue: 0,
    matchedProduct: { name: "Diwali Collection Saree", variant: "Green · Size L", stock: 12, thumbnailUrl: "" },
    dropOffMinutes: 30,
  },
  {
    id: "mock-fu-004",
    name: "Sameer Gupta",
    contact: "+917700112244",
    channel: "TELEGRAM",
    lastActiveAt: hourAgo(1.5),
    conversationId: "mock-conv-fu-004",
    lastMessage: "What fabrics do you use for the kurtas?",
    intent: "BROWSING",
    status: "OPEN",
    assignedTo: null,
    priority: "NORMAL",
    agentAssigned: null,
    pendingOrderAmount: null,
    aiScore: 62,
    daysSinceActive: 0,
    hasAutoReply: false,
    botRepliedAt: null,
    reasoning: "General fabric inquiry — low urgency but indicates consideration stage.",
    pastOrders: 0,
    lifetimeValue: 0,
    matchedProduct: null,
    dropOffMinutes: 45,
  },
  {
    id: "mock-fu-005",
    name: "Lakshmi Narayan",
    contact: "+916655443322",
    channel: "WHATSAPP",
    lastActiveAt: minAgo(90),
    conversationId: "mock-conv-fu-005",
    lastMessage: "Can I exchange if size doesn't fit?",
    intent: "SUPPORT",
    status: "OPEN",
    assignedTo: null,
    priority: "NORMAL",
    agentAssigned: null,
    pendingOrderAmount: null,
    aiScore: 68,
    daysSinceActive: 0,
    hasAutoReply: false,
    botRepliedAt: null,
    reasoning: "Exchange policy question — post-purchase support signal. Resolving quickly increases repeat rate by 40%.",
    pastOrders: 3,
    lifetimeValue: 12800,
    matchedProduct: null,
    dropOffMinutes: 25,
  },

  // ──────────────────────────────────────
  // BROWSING (base: low aiScore, no intent signal)
  // These demonstrate auto-escalation (>2h → Follow Up, >6h → Claim Now)
  // ──────────────────────────────────────
  {
    id: "mock-br-001",
    name: "Sneha Kapoor",
    contact: "@sneha_k",
    channel: "INSTAGRAM",
    lastActiveAt: hourAgo(3),   // > 2h → auto-promotes to Follow Up
    conversationId: "mock-conv-br-001",
    lastMessage: "Nice collection! Will check and get back",
    intent: "BROWSING",
    status: "OPEN",
    assignedTo: null,
    priority: "LOW",
    agentAssigned: null,
    pendingOrderAmount: null,
    aiScore: 30,
    daysSinceActive: 0,
    hasAutoReply: false,
    botRepliedAt: null,
    reasoning: "Compliment but no clear intent — may need gentle nudge with a curated recommendation.",
    pastOrders: 0,
    lifetimeValue: 0,
    matchedProduct: null,
    dropOffMinutes: 120,
  },
  {
    id: "mock-br-002",
    name: "Arjun Nair",
    contact: "+919900112233",
    channel: "TELEGRAM",
    lastActiveAt: hourAgo(24),  // > 6h → auto-promotes to Claim Now
    conversationId: "mock-conv-br-002",
    lastMessage: "Thanks, I'll think about it and let you know",
    intent: "BROWSING",
    status: "OPEN",
    assignedTo: null,
    priority: "LOW",
    agentAssigned: null,
    pendingOrderAmount: null,
    aiScore: 20,
    daysSinceActive: 1,
    hasAutoReply: false,
    botRepliedAt: null,
    reasoning: "Expressed gratitude — polite exit signal. Low conversion probability without re-engagement.",
    pastOrders: 0,
    lifetimeValue: 0,
    matchedProduct: null,
    dropOffMinutes: 180,
  },
  {
    id: "mock-br-003",
    name: "Neha Singh",
    contact: "neha.singh@email.com",
    channel: "WEBSITE",
    lastActiveAt: hourAgo(4),   // > 2h → auto-promotes to Follow Up
    conversationId: "mock-conv-br-003",
    lastMessage: "Just browsing your diwali collection, will order soon",
    intent: "BROWSING",
    status: "OPEN",
    assignedTo: null,
    priority: "LOW",
    agentAssigned: null,
    pendingOrderAmount: null,
    aiScore: 25,
    daysSinceActive: 0,
    hasAutoReply: false,
    botRepliedAt: null,
    reasoning: "Browsing Diwali collection — seasonal window. Capture attention with festive discount offer.",
    pastOrders: 1,
    lifetimeValue: 3200,
    matchedProduct: null,
    dropOffMinutes: 60,
  },
  {
    id: "mock-br-004",
    name: "Rohan Desai",
    contact: "@rohan_d",
    channel: "INSTAGRAM",
    lastActiveAt: minAgo(30),   // < 2h → stays Browsing
    conversationId: "mock-conv-br-004",
    lastMessage: "Love your work! Following from a while",
    intent: "BROWSING",
    status: "OPEN",
    assignedTo: null,
    priority: "LOW",
    agentAssigned: null,
    pendingOrderAmount: null,
    aiScore: 15,
    daysSinceActive: 0,
    hasAutoReply: false,
    botRepliedAt: null,
    reasoning: "Long-time follower — brand affinity exists. Personalised offer may trigger first purchase.",
    pastOrders: 0,
    lifetimeValue: 0,
    matchedProduct: null,
    dropOffMinutes: 90,
  },
  {
    id: "mock-br-005",
    name: "Pooja Reddy",
    contact: "+918877665544",
    channel: "TELEGRAM",
    lastActiveAt: minAgo(15),   // < 2h → stays Browsing
    conversationId: "mock-conv-br-005",
    lastMessage: "Hi, just looking around. Will DM if I need anything",
    intent: "BROWSING",
    status: "OPEN",
    assignedTo: null,
    priority: "LOW",
    agentAssigned: null,
    pendingOrderAmount: null,
    aiScore: 10,
    daysSinceActive: 0,
    hasAutoReply: false,
    botRepliedAt: null,
    reasoning: "Low-intent browsing — no immediate action needed. May respond to a limited-time offer.",
    pastOrders: 0,
    lifetimeValue: 0,
    matchedProduct: null,
    dropOffMinutes: 120,
  },
];

// ── Simulated incoming lead (arrives via "websocket" during demo) ──
let _incomingCounter = 0;

export function generateIncomingLead(): BackendLead {
  _incomingCounter++;
  const names = ["Divya Menon", "Akash Singh", "Farida Khan", "Manoj Pillai", "Rita Basu"];
  const channels = ["WHATSAPP", "INSTAGRAM", "WEBSITE", "TELEGRAM"] as const;
  const messages = [
    "Hello! How much for the silk saree?",
    "Do you ship to the US?",
    "I need a gift wrap option please",
    "Can I see more photos of this design?",
    "Is this still available?",
  ];
  const idx = _incomingCounter % names.length;
  const cdx = _incomingCounter % channels.length;
  const mdx = _incomingCounter % messages.length;

  return {
    id: `mock-incoming-${Date.now()}-${_incomingCounter}`,
    name: names[idx],
    contact: `+9199${String(_incomingCounter).padStart(8, "0")}`,
    channel: channels[cdx],
    lastActiveAt: new Date().toISOString(),
    conversationId: `mock-conv-incoming-${_incomingCounter}`,
    lastMessage: messages[mdx],
    intent: "BROWSING",
    status: "OPEN",
    assignedTo: null,
    priority: "LOW",
    agentAssigned: null,
    pendingOrderAmount: null,
    aiScore: Math.floor(Math.random() * 40) + 10,
    daysSinceActive: 0,
    hasAutoReply: false,
    botRepliedAt: null,
    reasoning: "New conversation — AI analysing intent patterns.",
    pastOrders: 0,
    lifetimeValue: 0,
    matchedProduct: null,
    dropOffMinutes: 15,
  };
}
